- name: catalogue configure
  hosts: catalogue
  become: yes
  tasks: 
  - name: enable nodejs 20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present
  
  - name: create system user
    ansible.builtin.user:

